// <auto-generated />
using System;
using MEGA_PROMOS.Api.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MEGA_PROMOS.Api.Migrations
{
    [DbContext(typeof(SuscriptorDbContext))]
    [Migration("20250628160808_BaseInicial")]
    partial class BaseInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MEGA_PROMOS.Api.ColoniasModel.Colonias", b =>
                {
                    b.Property<int>("colonia_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("colonia_id"));

                    b.Property<string>("ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("colonia_id");

                    b.ToTable("Colonias");
                });

            modelBuilder.Entity("MEGA_PROMOS.Api.Model.SuscriptorData", b =>
                {
                    b.Property<int>("suscriptor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("suscriptor_id"));

                    b.Property<int>("colonia_id")
                        .HasColumnType("int");

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("suscriptor_id");

                    b.ToTable("Suscriptor");
                });

            modelBuilder.Entity("MEGA_PROMOS.Api.PaqXPromo.PaqXPromoData", b =>
                {
                    b.Property<int>("paquete_id")
                        .HasColumnType("int");

                    b.Property<int>("promocion_id")
                        .HasColumnType("int");

                    b.HasKey("paquete_id", "promocion_id");

                    b.ToTable("paquete_x_promocion");
                });

            modelBuilder.Entity("MEGA_PROMOS.Api.PaqXServ.PaqXServData", b =>
                {
                    b.Property<int>("paquete_id")
                        .HasColumnType("int");

                    b.Property<int>("servicio_id")
                        .HasColumnType("int");

                    b.HasKey("paquete_id", "servicio_id");

                    b.ToTable("paquete_x_servicios");
                });

            modelBuilder.Entity("MEGA_PROMOS.Api.PaquetesModel.PaquetesData", b =>
                {
                    b.Property<int>("paquete_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paquete_id"));

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_paquete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("paquete_id");

                    b.ToTable("paquetes");
                });

            modelBuilder.Entity("MEGA_PROMOS.Api.PromocionesModel.PromocionesData", b =>
                {
                    b.Property<int>("promocion_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("promocion_id"));

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("es_automatica")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipo_descuento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("promocion_id");

                    b.ToTable("promociones");
                });

            modelBuilder.Entity("MEGA_PROMOS.Api.ServiciosModel.ServiciosData", b =>
                {
                    b.Property<int>("servicio_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("servicio_id"));

                    b.Property<string>("nombre_servicio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("servicio_id");

                    b.ToTable("servicios");
                });

            modelBuilder.Entity("MEGA_PROMOS.Api.SuscXPaq.SuscXPaqData", b =>
                {
                    b.Property<int>("suscriptor_id")
                        .HasColumnType("int");

                    b.Property<int>("paquete_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_terminacion")
                        .HasColumnType("datetime2");

                    b.HasKey("suscriptor_id", "paquete_id", "fecha_inicio");

                    b.ToTable("suscriptores_x_paquete");
                });
#pragma warning restore 612, 618
        }
    }
}
